name: Terraform Deploy (FastAPI → ECS → API Gateway)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  APP_NAME: fastapi-bedrock

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------- AWS AUTH (OIDC) ----------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::831873947473:role/GitHubActionsTerraformRole
          aws-region: ${{ env.AWS_REGION }}

      # ---------- TERRAFORM ----------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # ---------- ECR LOGIN ----------
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ---------- BUILD & PUSH IMAGE ----------
      - name: Build and Push Docker image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_REPO=$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP_NAME}

          docker build -t ${APP_NAME}:latest .
          docker tag ${APP_NAME}:latest ${ECR_REPO}:latest
          docker push ${ECR_REPO}:latest
